apiVersion: v1
kind: Pod
metadata:
  name: ebpf-profiler
spec:
  hostPID: true
  containers:
  - name: ebpf-profiler
    image: {{BPF_TOOLS_IMAGE}}
    imagePullPolicy: Always
    securityContext:
      privileged: true
    command:
    - nsenter
    - --target
    - "1"
    - --uts
    - --ipc
    - --net
    - --pid
    - --
    - "/bin/bash"
    - "-c"
    - |-
      BPF_TOOLS_CONTAINERID=$(crictl ps | grep ${BPF_TOOLS_CONTAINER} | awk '{print $1}')
      BPF_TOOLS_PID=$(crictl inspect --output go-template --template '{{.info.pid}}' $BPF_TOOLS_CONTAINERID)
      echo "profiling pid $BPF_TOOLS_PID for seconds $BPF_TOOLS_SECONDS"
      BPF_TOOLS_SECONDS=$(echo $BPF_TOOLS_SECONDS | sed s/\"//g)
      profile-bpfcc -dF 99 -f $BPF_TOOLS_SECONDS -p $BPF_TOOLS_PID | /flamegraph.pl > /${BPF_TOOLS_CONTAINER}.svg
      echo "profiling complete"
      sleep 30s #gives our script chance to copy out the flamegraph
    env:
    - name: BPF_TOOLS_SECONDS
      value: "{{BPF_TOOLS_SECONDS}}"
    - name: BPF_TOOLS_POD
      value: {{BPF_TOOLS_POD}}
    - name: BPF_TOOLS_CONTAINER
      value: {{BPF_TOOLS_CONTAINER}}
    volumeMounts:
      - mountPath: /sys/kernel/debug
        name: kernel-debug
      - mountPath: /sys/fs/cgroup
        name: fs-cgroup
      - mountPath: /sys/fs/bpf
        name: fs-bpf
      - mountPath: /run/containerd
        name: run-containerd
  nodeSelector:
    kubernetes.io/hostname: {{BPF_TOOLS_NODE}} # you can bind to a specific agent
  imagePullSecrets:
  - name: registrykey
  volumes:
    - name: kernel-debug
      hostPath:
        path: /sys/kernel/debug
    - name: fs-cgroup
      hostPath:
        path: /sys/fs/cgroup
    - name: fs-bpf
      hostPath:
        path: /sys/fs/bpf
    - name: run-containerd
      hostPath:
        path: /run/containerd

